
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container <?php echo $this->data['page'] ?>">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" class="active" href=".">Faculty Page</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="calendar.html">Calendar</a></li>
				<li><a href="contact.html">Contact</a></li>
				<li><a href="pastcourses.html">Courses</a></li>
			</ul>
			<form class="navbar-form navbar-right" action="searchResults"
				method="get">
				<div class="form-group">
					<input id="search" type="text" placeholder="<?php if(isset($Viewbag->q)) echo $Viewbag->q; else echo "search"; ?>"
						class="form-control" autocomplete="off"
						name="q" />
				</div>
				<button type="submit" class="btn btn-success">
					<i class="icon-search"></i>&nbsp;&nbsp;Search
				</button>
			</form>
		</div>
		<!--/.navbar-collapse -->
	</div>
</div>
