<?php
$this->data['title'] = "Rich: BUS3140";
$this->layout("_layout.phtml");
?>
<?php \RHildred\Editable\Markdown::render("courses/BUS3140/schedule.md");
?>
<hr />
<div class="bookmark" id="lecture1">
<?php \RHildred\Editable\Markdown::render("courses/BUS3140/lecture1.md");
?>
</div>
<hr />
<div class="bookmark" id="lecture2">
<?php \RHildred\Editable\Markdown::render("courses/BUS3140/lecture2.md");
?>
</div>

