<?php
$this->data['title'] = "Rich's contact info";
$this->layout("_layout.phtml");
?>
<h2>Contact</h2>
<div class="row">
    <div class="col-md-8">
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <div style="overflow:hidden;height:500px;width:100%;">
            <div id="gmap_canvas" style="height:500px;width:100%;"></div>
            <style>
                #gmap_canvas img {
                    max-width: none!important;
                    background: none!important
                }
            </style><a class="google-map-code" href="http://www.trivoo.net/gutscheine/schwab/" id="get-map-data">www.trivoo.net</a>
        </div>
        <script type="text/javascript">
            function init_map() {
                var myOptions = {
                    scrollwheel: false,
                    zoom: 12,
                    center: new google.maps.LatLng(43.4531855, -80.55331509999996),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                marker = new google.maps.Marker({
                    map: map,
                    position: new google.maps.LatLng(43.4531855, -80.55331509999996)
                });
                infowindow = new google.maps.InfoWindow({
                    content: "<b>Salesucation.com Inc</b><br/>5-420 Erb St. West<br/> N2L 6K6 Waterloo"
                });
                google.maps.event.addListener(marker, "click", function () {
                    infowindow.open(map, marker);
                });
                infowindow.open(map, marker);
            }
            google.maps.event.addDomListener(window, 'load', init_map);
        </script>
    </div>
    <div class="col-md-4">
        <p>
            <!-- a href="http://ca.linkedin.com/in/rhildred"><img
		src="images/richard_hildred.jpeg" /> </a-->
            <a href="https://github.com/rhildred" target="_blank">
                <img src="images/github.svg" alt="github" title="github" height="100" />
            </a>
            <a href="https://ca.linkedin.com/in/rhildred" target="_blank">
                <img src="images/Linkedin.svg" alt="linkedin" title="linkedin" height="100" />
            </a>
            <script>
                document.write('<a href="mai' + 'lto:rhi' + 'ldred@gm' + 'ail.com">')
            </script>
            <img src="images/Envelope_email.svg" alt="linkedin" title="linkedin" height="100" />
            </a>
        </p>
        <?php \RHildred\Editable\Markdown::render( "articles/contact.md"); ?>
    </div>
</div>
