<?php
require_once 'lib/template.php';
$Viewbag->title = "Rich: CP102D";
layout("_layout.phtml");
?>
<?php
renderMarkdown("courses/CP102D/lecture1.md");
?>
<hr />
<div class="bookmark" id="lecture2">
<?php
renderMarkdown("courses/CP102D/lecture2.md");
?></div>
<hr />
<div class="bookmark" id="lecture3">
<?php
renderMarkdown("courses/CP102D/lecture3.md");
?></div>
<hr />
<div class="bookmark" id="lecture4">
<?php
renderMarkdown("courses/CP102D/lecture4.md");
?></div>
<hr />
<div class="bookmark" id="lecture5">
<?php
renderMarkdown("courses/CP102D/lecture5.md");
?></div>
<hr />
<div class="bookmark" id="lecture6">
<?php
renderMarkdown("courses/CP102D/lecture6.md");
?></div>
<hr />
<div class="bookmark" id="lecture7">
<?php
renderMarkdown("courses/CP102D/lecture7.md");
?></div>
