<?php
$this->data['title'] = "Rich: DSGN1210";
$this->layout("_layout.phtml");
?>
<?php
\RHildred\Editable\Markdown::render("courses/DSGN1210/Photoshop.md");
?>
<div class="bookmark">
<?php
\RHildred\Editable\Markdown::render("articles/MobileFirst.md");
?>
</div
<hr />
<div class="bookmark">
<?php
\RHildred\Editable\Markdown::render("articles/PhotoshopProject.md");
?>
</div>
<hr />
<div class="bookmark">
<?php
\RHildred\Editable\Markdown::render("articles/Vectors.md");
?>
</div>
<hr />
<div class="bookmark" id="test">
<?php
\RHildred\Editable\Markdown::render("courses/DSGN1210/test.md");
?>
</div>
