<?php
require_once 'lib/template.php';
$Viewbag->title = "Rich: DSGN1210";
layout("_layout.phtml");
?>
<?php
renderMarkdown("courses/DSGN1210/Photoshop.md");
?>
<div class="bookmark">
<?php
renderMarkdown("articles/MobileFirst.md");
?>
</div
<hr />
<div class="bookmark">
<?php
renderMarkdown("articles/PhotoshopProject.md");
?>
</div>
<hr />
<div class="bookmark">
<?php
renderMarkdown("articles/Vectors.md");
?>
</div>
<hr />
<div class="bookmark" id="test">
<?php
renderMarkdown("courses/DSGN1210/test.md");
?>
</div>
