<?php
$this->data['title'] = "Rich's interests";
$this->layout("_layout.phtml");
?>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<h1>Rich Hildred</h1>
		<p>"Creative Active Individuals can only grow up in a society that
			emphasizes learning instead of teaching." - Chris Alexander</p>
		<p>Read more about my learning interests below.</p>
	</div>
</div>
<?php \RHildred\Editable\Markdown::render('articles/phplite/PHPLite.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/SplitTesting.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/Hactivism.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/openSource.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/webDevelopment.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/brackets.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/javascriptEvents.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/assert-runner.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/js-toolbox.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/WebRTC.md') ?>
