<?php
$this->data['title'] = "Rich's interests";
$this->layout("_layout.phtml");
?>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<h1>Rich Hildred</h1>
		<p>"Creative Active Individuals can only grow up in a society that
			emphasizes learning instead of teaching." - Chris Alexander</p>
		<p>Read more about my learning interests below or proceed to a
			current course by clicking one of the buttons.</p>
		<p>
                <a class="btn btn-primary btn-lg"
				role="button" href="BUS3140.html#lecture2">BUS3140&nbsp;&nbsp;
				<i class="icon-arrow-right"></i></a>
                <a class="btn btn-primary btn-lg"
				role="button" href="COMP2280.html">COMP2280&nbsp;&nbsp;
				<i class="icon-arrow-right"></i></a>
                <a class="btn btn-primary btn-lg"
				role="button" href="INFO3160.html">INFO3160&nbsp;&nbsp;
				<i class="icon-arrow-right"></i></a>
                <a class="btn btn-primary btn-lg"
				role="button" href="PROG1940.html">PROG1940&nbsp;&nbsp;
				<i class="icon-arrow-right"></i></a>
		</p>
	</div>
</div>
<?php \RHildred\Editable\Markdown::render('articles/SplitTesting.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/Hactivism.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/openSource.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/webDevelopment.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/brackets.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/javascriptEvents.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/assert-runner.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/js-toolbox.md') ?>
<hr />
<?php \RHildred\Editable\Markdown::render('articles/WebRTC.md') ?>
