<?php
$this->data['title'] = "Rich: INFO2120";
$this->layout("_layout.phtml");
?>
<?php
\RHildred\Editable\Markdown::render("articles/INFO2120.md");
?>

<hr />
<div class="bookmark"><?php
\RHildred\Editable\Markdown::render("articles/INFO2120WhyCMS.md");
?></div>

<hr />
<div id="links" class="bookmark"><?php
\RHildred\Editable\Markdown::render("articles/INFO2120Links.md");
?>
</div>

<hr />
<div id="pages" class="bookmark">
    <?php
\RHildred\Editable\Markdown::render("articles/INFO2120Pages.md");
?></div>

<hr />
<div class="bookmark">
    <?php
\RHildred\Editable\Markdown::render("articles/INFO2120Permissions.md");
?></div>

<hr />
<div id="home" class="bookmark">
        <?php
\RHildred\Editable\Markdown::render("articles/INFO2120Home.md");
?></div>

<hr />
<div id="theming" class="bookmark">
            <?php
\RHildred\Editable\Markdown::render("articles/INFO2120Theming.md");
?></div>

<hr />
<div id="paypal" class="bookmark">
        <?php
\RHildred\Editable\Markdown::render("articles/PayPal.md");
?></div>

<hr />
<div id="forms" class="bookmark">
            <?php
\RHildred\Editable\Markdown::render("articles/INFO2120WebForms.md");
?></div>

