<?php
$this->data['title'] = "Rich: PROG8020";
$this->layout("_layout.phtml");
?>
<?php \RHildred\Editable\Markdown::render("courses/PROG8020/schedule.md");
?>
<hr />
<?php \RHildred\Editable\Markdown::render("articles/BuildingBlocks.md");
?>
<hr />
<div id="database" class="bookmark">
<?php \RHildred\Editable\Markdown::render("articles/Database.md");
?>
</div>
<hr />
<div id="parameters" class="bookmark">
<?php \RHildred\Editable\Markdown::render("articles/Parameters.md");
?>
</div>
<hr />
<div id="midterm" class="bookmark">
<?php \RHildred\Editable\Markdown::render("courses/PROG8020/midterm.md");
?>
</div>
<hr />
<div class="bookmark" id="staticFramework">
<?php \RHildred\Editable\Markdown::render("articles/staticFramework.md");
?>
</div>
<hr />
<div class="bookmark" id="js-toolbox">
<?php \RHildred\Editable\Markdown::render("articles/js-toolbox.md");
?>
</div>
<hr />
<div class="bookmark" id="javascriptEvents">
<?php \RHildred\Editable\Markdown::render("articles/javascriptEvents.md");
?>
</div>
<hr />
<div class="bookmark" id="ConsumingAPI">
<?php \RHildred\Editable\Markdown::render("articles/ConsumingAPI.md");
?>
</div>
<hr />
<div id="final" class="bookmark">
<?php \RHildred\Editable\Markdown::render("courses/PROG8020/final.md");
?>
</div>

