<?php
$this->data['title'] = "Rich: PROG1700";
$this->layout("_layout.phtml");
?>
<?php \RHildred\Editable\Markdown::render("courses/PROG1700/schedule.md");
?>
<hr />
<div class="bookmark" id="ResponsiveTruth">
<?php \RHildred\Editable\Markdown::render("articles/ResponsiveTruth.md");
?>
</div>
<hr />
<div class="bookmark" id="paypal">
<?php \RHildred\Editable\Markdown::render("articles/PayPal.md");
?>
</div>
<hr />
<div class="bookmark" id="exam">
<?php \RHildred\Editable\Markdown::render("courses/PROG1700/exam.md");
?>
</div>
