<?php
$this->data['title'] = "Rich: PROG1940";
$this->layout("_layout.phtml");
?>
<?php \RHildred\Editable\Markdown::render("courses/PROG1940/PROG1940.md");
?>
<hr />
<?php \RHildred\Editable\Markdown::render("articles/BuildingBlocks.md");
?>
<hr />
<div id="database" class="bookmark">
<?php \RHildred\Editable\Markdown::render("articles/Database.md");
?>
</div>
<hr />
<div id="parameters" class="bookmark">
<?php \RHildred\Editable\Markdown::render("articles/Parameters.md");
?>
</div>
<hr />
<div id="slim" class="bookmark">
<?php \RHildred\Editable\Markdown::render("courses/PROG1940/slim.md");
?>
</div><hr />
<div id="migrations" class="bookmark">
<?php \RHildred\Editable\Markdown::render("courses/PROG1940/migrations.md");
?>
</div><hr />
<div id="final" class="bookmark">
<?php \RHildred\Editable\Markdown::render("courses/PROG1940/final.md");
?>
</div>

