<?php
require_once 'lib/template.php';
$Viewbag->title = "Rich: PROG8110";
layout("_layout.phtml");
?>
<?php renderMarkdown("courses/PROG8110/schedule.md");
?>
<hr />
<div id="phonegapbuild" class="bookmark">
<?php renderMarkdown("courses/PROG8110/Phonegap.md");
?>
</div>
<hr />
<div id="webworks" class="bookmark">
<?php renderMarkdown("courses/PROG8110/Webworks.md");
?>
</div>
<hr />
<div id="node.js" class="bookmark">
<?php renderMarkdown("courses/PROG8110/Node.md");
?>
</div>
<hr />
<div id="jqm" class="bookmark">
<?php renderMarkdown("courses/PROG8110/jqm.md");
?>
</div>
<hr />
<div id="midterm" class="bookmark">
<?php renderMarkdown("courses/PROG8110/midterm.md");
?>
</div>
<hr />
<div id="angular" class="bookmark">
<?php renderMarkdown("courses/PROG8110/angular.md");
?>
</div>
<hr />
<div id="tdd" class="bookmark">
<?php renderMarkdown("courses/PROG8110/tdd.md");
?>
</div>
<hr />
<div id="youarehere" class="bookmark">
<?php renderMarkdown("courses/PROG8110/youarehere.md");
?>
</div>
<hr />
<div id="tellme" class="bookmark">
<?php renderMarkdown("courses/PROG8110/tellme.md");
?>
</div>
<hr />
<div id="final" class="bookmark">
<?php renderMarkdown("courses/PROG8110/final.md");
?>
</div>

