<?php
$this->data['title'] = "Rich: PROG1795";
$this->layout("_layout.phtml");
?>
<?php \RHildred\Editable\Markdown::render("courses/PROG1795/schedule.md");
?>
<hr />
<div class="bookmark" id="staticFramework">
<?php \RHildred\Editable\Markdown::render("articles/staticFramework.md");
?>
</div>
<hr />
<div class="bookmark" id="js-toolbox">
<?php \RHildred\Editable\Markdown::render("articles/js-toolbox.md");
?>
</div>
<hr />
<div class="bookmark" id="javascriptEvents">
<?php \RHildred\Editable\Markdown::render("articles/javascriptEvents.md");
?>
</div>
<hr />
<div class="bookmark" id="ConsumingAPI">
<?php \RHildred\Editable\Markdown::render("articles/ConsumingAPI.md");
?>
<hr />
<div class="bookmark" id="tdd">
<?php \RHildred\Editable\Markdown::render("courses/PROG1795/tdd.md");
?>
</div>
<hr />
<div class="bookmark" id="final">
<?php \RHildred\Editable\Markdown::render("courses/PROG1795/final.md");
?>
</div>
