<?php
$this->data['title'] = "Search Results";
$this->layout("_layout.phtml");
?>
<div id="results"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.2/marked.js"></script>
<script src="js/hilitor.js"></script>
<script type="text/javascript">
	var QueryString = function() {
		// This function is anonymous, is executed immediately and
		// the return value is assigned to QueryString!
		var query_string = {};
		var query = window.location.search.substring(1);
		var vars = query.split("&");
		for ( var i = 0; i < vars.length; i++) {
			var pair = vars[i].split("=");
			// If first entry with this name
			if (typeof query_string[pair[0]] === "undefined") {
				query_string[pair[0]] = pair[1];
				// If second entry with this name
			} else if (typeof query_string[pair[0]] === "string") {
				var arr = [ query_string[pair[0]], pair[1] ];
				query_string[pair[0]] = arr;
				// If third or later entry with this name
			} else {
				query_string[pair[0]].push(pair[1]);
			}
		}
		return query_string;
	}();

	var myHilitor = new Hilitor("results");
	myHilitor.setMatchType("open");
    sQuery = QueryString.q.replace('+', ' ');
    jQuery("#search").attr("placeholder", sQuery);
    jQuery.ajax({url: "https://rich-hildred.rhcloud.com/Results?q=" + QueryString.q, dataType: "json"}).done(function(aResults){
        var nLeft = aResults.length;
        for(var n = 0; n < aResults.length; n++){
            var sUrl = aResults[n].id;
            jQuery.ajax(sUrl).done(function(sMd){
                jQuery("#results").append(marked(sMd));
                if(--nLeft == 0)myHilitor.apply(sQuery);
            });
        }

    });

</script>
